MISRA: Debug step commented out

diff --git a/.github/workflows/ci-project.yml b/.github/workflows/ci-project.yml
--- a/.github/workflows/ci-project.yml
+++ b/.github/workflows/ci-project.yml
@@ -147,21 +147,21 @@ jobs:
         mkdir -p  _build
         tar -xvf build-${{ matrix.target }}.tar -C _build
 
-    - name: Debug list unpacked build dir
-      run: |
-        pwd
-        set -e
-        echo "Listing _build top-level"
-        ls -la _build || true
-        echo "Listing target dir"
-        ls -la _build/${{ matrix.target }} || true
-        if [ -f _build/${{ matrix.target }}/compile_commands.json ]; then
-          echo "FOUND: _build/${{ matrix.target }}/compile_commands.json"
-        else
-          echo "MISSING: compile_commands.json"
-          ls -R _build
-          exit 1
-        fi
+#    - name: Debug list unpacked build dir
+#      run: |
+#        pwd
+#        set -e
+#        echo "Listing _build top-level"
+#        ls -la _build || true
+#        echo "Listing target dir"
+#        ls -la _build/${{ matrix.target }} || true
+#        if [ -f _build/${{ matrix.target }}/compile_commands.json ]; then
+#          echo "FOUND: _build/${{ matrix.target }}/compile_commands.json"
+#        else
+#          echo "MISSING: compile_commands.json"
+#          ls -R _build
+#          exit 1
+#        fi
 
 
     # Runs code analysis with C/C++test.
