MISRA: Project CI test

diff --git a/.github/workflows/ci-project.yml b/.github/workflows/ci-project.yml
--- a/.github/workflows/ci-project.yml
+++ b/.github/workflows/ci-project.yml
@@ -20,6 +20,23 @@ on:
         default: false
         required: false
 
+    workflow_dispatch:
+    inputs:
+      logLevel:
+        description: 'Log level'
+        required: true
+        default: 'warning'
+        type: choice
+        options:
+        - info
+        - warning
+        - debug
+      tags:
+        description: 'Test scenario tags'
+        required: false
+        type: boolean
+
+
 
 # jobs
 jobs:
@@ -29,27 +46,27 @@ jobs:
     strategy:
       matrix:
         target:
-          - 'armv7a7-imx6ull-evk'
+#          - 'armv7a7-imx6ull-evk'
           - 'armv7a9-zynq7000-qemu'
-          - 'armv7a9-zynq7000-zedboard'
-          - 'armv7a9-zynq7000-zturn'
-          - 'armv7m4-stm32l4x6-nucleo'
-          - 'armv7m7-imxrt105x-evk'
-          - 'armv7m7-imxrt106x-evk'
-          - 'armv7m7-imxrt117x-evk'
-          - 'armv8r52-mps3an536-qemu'
-          - 'armv8m33-mcxn94x-frdm'
-          - 'aarch64a53-zynqmp-qemu'
-          - 'host-generic-pc'
-          - 'ia32-generic-pc'
-          - 'ia32-generic-qemu'
-          - 'riscv64-generic-qemu'
-          - 'riscv64-grfpga-artya7'
-          - 'sparcv8leon-generic-qemu'
-          - 'sparcv8leon-gr712rc-board'
-          - 'sparcv8leon-gr716-mimas'
-          - 'sparcv8leon-gr716-mini'
-          - 'sparcv8leon-gr740-mini'
+#          - 'armv7a9-zynq7000-zedboard'
+#          - 'armv7a9-zynq7000-zturn'
+#          - 'armv7m4-stm32l4x6-nucleo'
+#          - 'armv7m7-imxrt105x-evk'
+#          - 'armv7m7-imxrt106x-evk'
+#          - 'armv7m7-imxrt117x-evk'
+#          - 'armv8r52-mps3an536-qemu'
+#          - 'armv8m33-mcxn94x-frdm'
+#          - 'aarch64a53-zynqmp-qemu'
+#          - 'host-generic-pc'
+#          - 'ia32-generic-pc'
+#          - 'ia32-generic-qemu'
+#          - 'riscv64-generic-qemu'
+#          - 'riscv64-grfpga-artya7'
+#          - 'sparcv8leon-generic-qemu'
+#          - 'sparcv8leon-gr712rc-board'
+#          - 'sparcv8leon-gr716-mimas'
+#          - 'sparcv8leon-gr716-mini'
+#          - 'sparcv8leon-gr740-mini'
         include:
           - target: 'armv7a9-zynq7000-qemu'
             additional_params: 'ports'
@@ -93,142 +110,218 @@ jobs:
             boot-${{ matrix.target }}.tar
             rootfs-${{ matrix.target }}.tar
 
-  test-emu:
+  run-cpptest:
     needs: build
-    name: test EMU
-    runs-on: ubuntu-latest
+    name: Analyze project with C/C++test
+    runs-on: self-hosted
+
+    container:
+      image: cpt
     strategy:
       fail-fast: false
       matrix:
-        target: ['armv7a9-zynq7000-qemu', 'host-generic-pc', 'ia32-generic-qemu', 'riscv64-generic-qemu', 'sparcv8leon-generic-qemu', 'aarch64a53-zynqmp-qemu']
+        target: ['armv7a9-zynq7000-qemu'] #, 'host-generic-pc', 'ia32-generic-qemu', 'riscv64-generic-qemu', 'sparcv8leon-generic-qemu', 'aarch64a53-zynqmp-qemu']
 
+    # Specifies required permissions for upload-sarif action
+    permissions:
+      # required for all workflows
+      security-events: write
+      # only required for workflows in private repositories
+      pull-requests: write 
+      actions: read
+      contents: read
+
+    # Steps represent a sequence of tasks that will be executed as part of the job.
     steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
+    # Setup reviedog
+    - name: ReviewDog setup
+      uses: reviewdog/action-setup@v1
+      if: true
 
-      - name: Download build artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: phoenix-rtos-${{ matrix.target }}
+    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Untar rootfs
-        working-directory: _fs
-        run: tar -xvf ../rootfs-${{ matrix.target }}.tar
-
-      - name: Create empty _boot
-        run: mkdir _boot
-
-      - name: Untar boot
-        working-directory: _boot
-        run: tar -xvf ../boot-${{ matrix.target }}.tar
-
-      - name: Add sanitizers problem matcher
-        run: echo "::add-matcher::.github/problem-matchers/sanitizer-errors.json"
-
-      - name: Test runner
-        id: runner
-        uses: ./.github/actions/phoenix-runner
-        with:
-          image-tag: ${{ inputs.image-tag }}
-          target: ${{ matrix.target }}
-          nightly: ${{ inputs.nightly }}
-
-      - name: Upload runner results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-results-${{ matrix.target }}
-          path: |
-            results.csv
-            results.xml
-
-  test-hw:
-    needs: build
-    name: test HW
-    runs-on: ${{ matrix.target }}
-    strategy:
-      fail-fast: false
-      matrix:
-        target: ['armv7a7-imx6ull-evk', 'armv7m7-imxrt106x-evk', 'armv7m7-imxrt117x-evk', 'armv7a9-zynq7000-zedboard', 'armv7m4-stm32l4x6-nucleo']
-
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
-
-      - name: Download build artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: phoenix-rtos-${{ matrix.target }}
-
-      - name: Untar rootfs
-        working-directory: _fs
-        run: tar -xvf ../rootfs-${{ matrix.target }}.tar
-
-      - name: Create empty _boot
-        run: mkdir _boot
-
-      - name: Untar boot
-        working-directory: _boot
-        run: tar -xvf ../boot-${{ matrix.target }}.tar
-
-      - name: Test runner
-        id: runner
-        run: |
-          python3 ./phoenix-rtos-tests/runner.py -v -T${{ matrix.target }} ${{ inputs.nightly && '--nightly' || '' }} -Oresults.csv
-
-      - name: Upload runner results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-results-${{ matrix.target }}
-          path: |
-            results.csv
-            results.xml
-
-  tests-summary:
-    if: success() || failure()   # don't care about cancelled runs
-    needs: ['test-emu', 'test-hw']
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: artifacts
-          pattern: test-results-*
-
-      - name: Display structure of downloaded files
-        run: ls -R
-
-      - name: Merge Test Results
-        run: |
-          pip3 install junitparser junit2html
-          junitparser merge artifacts/test-results-*/results.xml junit.xml
-          junit2html junit.xml junit.html
-        env:
-          PIP_BREAK_SYSTEM_PACKAGES: 1  # NOTE: we're running on emphemeral GH VMs, install packages globally
-
-      - name: Upload Merged Unit Test Results in HTML
-        uses: actions/upload-artifact@v4
-        with:
-          name: Merged Unit Test Results
-          if-no-files-found: ignore
-          path: |
-            junit.html
-            junit.xml
-
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        with:
-          check_name: Unit Test Results
-          files: "junit.xml"
+    - name: Download build artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: phoenix-rtos-${{ matrix.target }}
 
 
-  send-notification:
-    needs: ['build', 'test-emu', 'test-hw']
-    if: failure() && github.event_name != 'pull_request'
-    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/_send_google_chat.yml@master
-    secrets: inherit
+    # Runs code analysis with C/C++test.
+    - name: Run C/C++test
+      # Use the 'run-cpptest-action' GitHub action.
+      uses: parasoft/run-cpptest-action@2.0.2
+      # Optional parameters for 'run-cpptest-action'.
+      with:
+        # For CMake-based projects, use a compile_commands.json file as the input for analysis. 
+        input: _build/${{ matrix.target }}/compile_commands.json
+        testConfig: 'builtin://MISRA C 2023 (MISRA C 2012)'
+        # Uncomment if you are using C/C++test 2020.2 to generate a SARIF report:
+        # reportFormat: xml,html,custom
+        # additionalParams: '-property report.custom.extension=sarif -property report.custom.xsl.file=${PARASOFT_SARIF_XSL}'
+
+    # Run Reviewdog
+    - name: Run Reviewdog
+      if: always()
+      uses: github/codeql-action/upload-sarif@v3
+      with:
+        sarif_file: reports/report.sarif
+
+    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
+    - name: Upload results (SARIF)
+      if: always()
+      shell: bash  # will enforce -o pipefail
+      env:
+        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        cat reports/report.sarif | reviewdog -f=sarif -diff="git diff -U0 HEAD^" -name=cpptest-pr -reporter=github-pr-review -fail-on-error
+
+    # Uploads an archive that includes all report files (.xml, .html, .sarif).
+    - name: Archive reports
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: CpptestReports
+        path: reports/*.*
+#
+#  test-emu:
+#    needs: build
+#    name: test EMU
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        target: ['armv7a9-zynq7000-qemu', 'host-generic-pc', 'ia32-generic-qemu', 'riscv64-generic-qemu', 'sparcv8leon-generic-qemu', 'aarch64a53-zynqmp-qemu']
+#
+#    steps:
+#      - name: Checkout the repository
+#        uses: actions/checkout@v4
+#        with:
+#          submodules: recursive
+#
+#      - name: Download build artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: phoenix-rtos-${{ matrix.target }}
+#
+#      - name: Untar rootfs
+#        working-directory: _fs
+#        run: tar -xvf ../rootfs-${{ matrix.target }}.tar
+#
+#      - name: Create empty _boot
+#        run: mkdir _boot
+#
+#      - name: Untar boot
+#        working-directory: _boot
+#        run: tar -xvf ../boot-${{ matrix.target }}.tar
+#
+#      - name: Add sanitizers problem matcher
+#        run: echo "::add-matcher::.github/problem-matchers/sanitizer-errors.json"
+#
+#      - name: Test runner
+#        id: runner
+#        uses: ./.github/actions/phoenix-runner
+#        with:
+#          image-tag: ${{ inputs.image-tag }}
+#          target: ${{ matrix.target }}
+#          nightly: ${{ inputs.nightly }}
+#
+#      - name: Upload runner results
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: test-results-${{ matrix.target }}
+#          path: |
+#            results.csv
+#            results.xml
+#
+#  test-hw:
+#    needs: build
+#    name: test HW
+#    runs-on: ${{ matrix.target }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        target: ['armv7a7-imx6ull-evk', 'armv7m7-imxrt106x-evk', 'armv7m7-imxrt117x-evk', 'armv7a9-zynq7000-zedboard', 'armv7m4-stm32l4x6-nucleo']
+#
+#    steps:
+#      - name: Checkout the repository
+#        uses: actions/checkout@v4
+#        with:
+#          submodules: recursive
+#
+#      - name: Download build artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: phoenix-rtos-${{ matrix.target }}
+#
+#      - name: Untar rootfs
+#        working-directory: _fs
+#        run: tar -xvf ../rootfs-${{ matrix.target }}.tar
+#
+#      - name: Create empty _boot
+#        run: mkdir _boot
+#
+#      - name: Untar boot
+#        working-directory: _boot
+#        run: tar -xvf ../boot-${{ matrix.target }}.tar
+#
+#      - name: Test runner
+#        id: runner
+#        run: |
+#          python3 ./phoenix-rtos-tests/runner.py -v -T${{ matrix.target }} ${{ inputs.nightly && '--nightly' || '' }} -Oresults.csv
+#
+#      - name: Upload runner results
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: test-results-${{ matrix.target }}
+#          path: |
+#            results.csv
+#            results.xml
+#
+#  tests-summary:
+#    if: success() || failure()   # don't care about cancelled runs
+#    needs: ['test-emu', 'test-hw']
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Download Artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          path: artifacts
+#          pattern: test-results-*
+#
+#      - name: Display structure of downloaded files
+#        run: ls -R
+#
+#      - name: Merge Test Results
+#        run: |
+#          pip3 install junitparser junit2html
+#          junitparser merge artifacts/test-results-*/results.xml junit.xml
+#          junit2html junit.xml junit.html
+#        env:
+#          PIP_BREAK_SYSTEM_PACKAGES: 1  # NOTE: we're running on emphemeral GH VMs, install packages globally
+#
+#      - name: Upload Merged Unit Test Results in HTML
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: Merged Unit Test Results
+#          if-no-files-found: ignore
+#          path: |
+#            junit.html
+#            junit.xml
+#
+#      - name: Publish Unit Test Results
+#        uses: EnricoMi/publish-unit-test-result-action@v2
+#        with:
+#          check_name: Unit Test Results
+#          files: "junit.xml"
+#
+#
+#  send-notification:
+#    needs: ['build', 'test-emu', 'test-hw']
+#    if: failure() && github.event_name != 'pull_request'
+#    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/_send_google_chat.yml@master
+#    secrets: inherit
+#
