MISRA: CI corrections

diff --git a/.github/workflows/ci-submodule.yml b/.github/workflows/ci-submodule.yml
--- a/.github/workflows/ci-submodule.yml
+++ b/.github/workflows/ci-submodule.yml
@@ -104,6 +104,7 @@ jobs:
           path: |
             ${{env.BUILD_DIRECTORY}}/_boot/${{ matrix.target }}
             ${{env.BUILD_DIRECTORY}}/rootfs-${{ matrix.target }}.tar
+            ${{env.BUILD_DIRECTORY}}/_build/${{ matrix.target }}
 
   test-emu:
     needs: build
@@ -157,93 +158,94 @@ jobs:
             results.csv
             results.xml
 
-  # runs on self-hosted runners with HW targets attached
-  test-hw:
-    needs: build
-    name: test HW
-    runs-on: ${{ matrix.target }}
-    strategy:
-      fail-fast: false
-      matrix:
-        target: ['armv7a7-imx6ull-evk', 'armv7m7-imxrt106x-evk', 'armv7m7-imxrt117x-evk', 'armv7a9-zynq7000-zedboard', 'armv7m4-stm32l4x6-nucleo']
-
-    steps:
-      - name: Checkout phoenix-rtos-project
-        uses: actions/checkout@v4
-        with:
-          repository: phoenix-rtos/phoenix-rtos-project
-          submodules: recursive
-
-      - name: Update submodule ${{ github.event.repository.name }}
-        working-directory: ${{ github.event.repository.name }}
-        run: |
-          git fetch --recurse-submodules=no --force ${{ github.event.repository.clone_url }} "+refs/heads/*:refs/remotes/origin/*"
-          git fetch --recurse-submodules=no --force ${{ github.event.repository.clone_url }} "+refs/pull/*/head:refs/remotes/origin/pr/*"
-          git checkout ${{ github.sha }} || git checkout ${{ github.event.pull_request.head.sha }}
-
-      - name: Download build artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: phoenix-rtos-${{ matrix.target }}
-
-      - name: Untar rootfs
-        working-directory: _fs
-        run: tar -xvf ../rootfs-${{ matrix.target }}.tar
-
-      - name: Test runner
-        id: runner
-        run: |
-          python3 ./phoenix-rtos-tests/runner.py -v -T${{ matrix.target }} ${{ inputs.nightly && '--nightly' || '' }} -Oresults.csv
-
-      - name: Upload runner results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-results-${{ matrix.target }}
-          path: |
-            results.csv
-            results.xml
-
-  tests-summary:
-    if: success() || failure()   # don't care about cancelled runs
-    needs: ['test-emu', 'test-hw']
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: artifacts
-          pattern: test-results-*
-
-      - name: Display structure of downloaded files
-        run: ls -R
-
-      - name: Merge Test Results
-        run: |
-          pip3 install junitparser junit2html
-          junitparser merge artifacts/test-results-*/results.xml junit.xml
-          junit2html junit.xml junit.html
-        env:
-          PIP_BREAK_SYSTEM_PACKAGES: 1  # NOTE: we're running on emphemeral GH VMs, install packages globally
-
-      - name: Upload Merged Unit Test Results in HTML
-        uses: actions/upload-artifact@v4
-        with:
-          name: Merged Unit Test Results
-          if-no-files-found: ignore
-          path: |
-            junit.html
-            junit.xml
-
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        with:
-          check_name: Unit Test Results
-          files: "junit.xml"
-
-
-  send-notification:
-    needs: ['build', 'test-emu', 'test-hw']
-    if: failure() && github.event_name != 'pull_request'
-    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/_send_google_chat.yml@master
-    secrets: inherit
+  ## runs on self-hosted runners with HW targets attached
+  #test-hw:
+  #  needs: build
+  #  name: test HW
+  #  runs-on: ${{ matrix.target }}
+  #  strategy:
+  #    fail-fast: false
+  #    matrix:
+  #      target: ['armv7a7-imx6ull-evk', 'armv7m7-imxrt106x-evk', 'armv7m7-imxrt117x-evk', 'armv7a9-zynq7000-zedboard', 'armv7m4-stm32l4x6-nucleo']
+#
+  #  steps:
+  #    - name: Checkout phoenix-rtos-project
+  #      uses: actions/checkout@v4
+  #      with:
+  #        repository: phoenix-rtos/phoenix-rtos-project
+  #        submodules: recursive
+#
+  #    - name: Update submodule ${{ github.event.repository.name }}
+  #      working-directory: ${{ github.event.repository.name }}
+  #      run: |
+  #        git fetch --recurse-submodules=no --force ${{ github.event.repository.clone_url }} "+refs/heads/*:refs/remotes/origin/*"
+  #        git fetch --recurse-submodules=no --force ${{ github.event.repository.clone_url }} "+refs/pull/*/head:refs/remotes/origin/pr/*"
+  #        git checkout ${{ github.sha }} || git checkout ${{ github.event.pull_request.head.sha }}
+#
+  #    - name: Download build artifacts
+  #      uses: actions/download-artifact@v4
+  #      with:
+  #        name: phoenix-rtos-${{ matrix.target }}
+#
+  #    - name: Untar rootfs
+  #      working-directory: _fs
+  #      run: tar -xvf ../rootfs-${{ matrix.target }}.tar
+#
+  #    - name: Test runner
+  #      id: runner
+  #      run: |
+  #        python3 ./phoenix-rtos-tests/runner.py -v -T${{ matrix.target }} ${{ inputs.nightly && '--nightly' || '' }} -Oresults.csv
+#
+  #    - name: Upload runner results
+  #      if: always()
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: test-results-${{ matrix.target }}
+  #        path: |
+  #          results.csv
+  #          results.xml
+#
+  #tests-summary:
+  #  if: success() || failure()   # don't care about cancelled runs
+  #  needs: ['test-emu', 'test-hw']
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #    - name: Download Artifacts
+  #      uses: actions/download-artifact@v4
+  #      with:
+  #        path: artifacts
+  #        pattern: test-results-*
+#
+  #    - name: Display structure of downloaded files
+  #      run: ls -R
+#
+  #    - name: Merge Test Results
+  #      run: |
+  #        pip3 install junitparser junit2html
+  #        junitparser merge artifacts/test-results-*/results.xml junit.xml
+  #        junit2html junit.xml junit.html
+  #      env:
+  #        PIP_BREAK_SYSTEM_PACKAGES: 1  # NOTE: we're running on emphemeral GH VMs, install packages globally
+#
+  #    - name: Upload Merged Unit Test Results in HTML
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: Merged Unit Test Results
+  #        if-no-files-found: ignore
+  #        path: |
+  #          junit.html
+  #          junit.xml
+#
+  #    - name: Publish Unit Test Results
+  #      uses: EnricoMi/publish-unit-test-result-action@v2
+  #      with:
+  #        check_name: Unit Test Results
+  #        files: "junit.xml"
+#
+#
+  #send-notification:
+  #  needs: ['build', 'test-emu', 'test-hw']
+  #  if: failure() && github.event_name != 'pull_request'
+  #  uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/_send_google_chat.yml@master
+  #  secrets: inherit
+#
